services:
  backend:
    build: .
    working_dir: /backend
    command: uvicorn src.app:app --host 0.0.0.0 --reload --port 8000
    container_name: backend
    volumes:
      - .:/backend
    env_file: ".env.dev"
    ports:
      - "8000:8000"
    depends_on:
      - backend-db
    networks:
      - default
      - ai_shared_network  

  backend-worker:
    build: .
    working_dir: /backend
    command: [ 'celery', '-A', 'src.worker.celery_app', 'worker', '-l', 'info' ]
    container_name: backend-worker
    env_file: ".env.dev"
    volumes:
      - .:/backend
    depends_on:
      - backend-db
      - backend-redis
    networks:
      - default
      - ai_shared_network  

  backend-db:
    image: postgres:latest
    container_name: backend-db
    ports:
      - "5433:5432"
    env_file: ".env.dev"
    volumes:
      - backend-db-volume:/var/lib/postgresql

  backend-redis:
    image: redis:latest
    container_name: backend-redis

networks:
  default:
  ai_shared_network:
    external: true

volumes:
  backend-db-volume:
