"""add_file_hash

Revision ID: 2957aa12056d
Revises: f5fd778d27ad
Create Date: 2026-04-22 06:20:59.417947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2957aa12056d'
down_revision: Union[str, Sequence[str], None] = 'f5fd778d27ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index('idx_file_hash_size', 'files', ['file_hash', 'size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_hash_size', table_name='files')
    op.drop_column('files', 'file_hash')
    # ### end Alembic commands ###
